### ISSUE TITLE
Definition of Persistence and Liveness

### ISSUE THREAD

**Issue by saltiniroberto** [EntEthAlliance/enhanced-bft#1]
**[GPAv1](https://member.entethalliance.org/HigherLogic/System/DownloadDocumentFile.ashx?DocumentFileKey=8eaf71f6-6cd1-4720-bada-4c7f3030197c) feedback**
GPAv1 expresses concerns around the usage of the Persistence property and indicates that the definition of Persistence seems like an overlap with the definition of Liveness.

**Reply**
The “Correctness Analysis of IBFT” and “IBFT 2.0 Gray Paper” papers use a definition of Robustness for a distributed ledger which is in alignment with the literature in this area. Specifically, the Robustness, Persistence and Liveness properties as stated in the “Correctness Analysis of IBFT” and “IBFT 2.0 Gray Paper”  have been introduced by Garay et al. (2015) (https://eprint.iacr.org/2014/765)
They have also been used in the following academic papers:

- Ouroboros: A Provably Secure Proof-of-Stake Blockchain Protocol (https://eprint.iacr.org/2016/889)
- Analysis of the Blockchain Protocol in Asynchronous Networks (https://eprint.iacr.org/2016/454) 
- Speed-Security Tradeoffs in Blockchain Protocols (https://eprint.iacr.org/2015/1019)

**Comment by kubasiemion** [comment]
Closing, as we have agreed to include the relevant content into Glossary and Assumptions (meerting 31.07.2019)
