### ISSUE TITLE
A practical proof the persistence issue of IBFT exists

### ISSUE THREAD

**Issue by saltiniroberto** [EntEthAlliance/enhanced-bft#10]
**[GPAv1](https://member.entethalliance.org/HigherLogic/System/DownloadDocumentFile.ashx?DocumentFileKey=8eaf71f6-6cd1-4720-bada-4c7f3030197c) feedback**
The GPAv1 document states that the safety and liveness issues identified in the “Correctness Analysis of IBFT” paper are based on weak assumptions, lack practical evidence and the limitations cannot be concretely reproduced.

**Reply**
 The persistence issue , namely that a network of 6 validators can fork even though all validators are honest can be proven in the following way:

1. Start an IBFT network of 6 validators (using docker compose)
2. Verify via the network scanner that all 6 validators are running
3. Stop 3 validators (e.g. by killing the related docker instances)
4. Verify that the network is still creating new blocks.

This proves that in a network of 6 validators, 3 validators can create new blocks without requiring communication with any of the other 3 validators. It is therefore possible for the first 3 validators to create block _B_ at height _h_ and for the other 3 validators to create a block _B’_, different from _B_, at the same height _h_.

**Comment by chaals** [comment]
Agreed 2020-05-27 to close this issue
