### ISSUE TITLE
System Model Assumptions

### ISSUE THREAD

**Issue by saltiniroberto** [EntEthAlliance/enhanced-bft#12]
This is a meta-issue whose objective is to list all the issues that describe system model assumptions under which design, specify and prove the correctness of the consensus protocol.

- Definition of Robustness: #14 
  Please note that this is where finality is defined
- Network Model: #4 
- Fault-Tolerance: #13 
- Permissioning for block creation: #15 
- Permissioning for read acceess: #17 
- Privacy Layer Integration: #18 
- Cryptographic Assumptions: #16

**Comment by kubasiemion** [comment]
I suggest that we separate agreeing on glossary (first) from agreeing on assumptions (second).

**Comment by kubasiemion** [comment]
Waiting to be closed after Assumptions section is initiated by Roberto.

**Comment by chaals** [comment]
Agreed 2020-05-27 to close this
