### ISSUE TITLE
Fault-Tolerance

### ISSUE THREAD

**Issue by saltiniroberto** [EntEthAlliance/enhanced-bft#13]
The *BFT Consnesus Protocol must withstand Byzantine actors.

Also, the protocol must provide optimal Byzantine-fault-tolerance. This means that in a network of `n` nodes the protocol must be able to ensure robustness (see #14 for a definition) even if up to `floor((n-1)/3)` of the nodes are Byzantine

**Comment by drequinox** [comment]
Agreed

**Comment by kubasiemion** [comment]
Closing, as we have agreed to include the relevant content into Glossary and Assumptions (meeting 31.07.2019)
