### ISSUE TITLE
Cryptographic Assumptions

### ISSUE THREAD

**Issue by saltiniroberto** [EntEthAlliance/enhanced-bft#16]
The Keccak hash function is assumed to be collision-resistant.

The standard Ethereum ECDSA signing algorithm is assumed to guarantee uniqueness and unforgeability.

**Comment by drequinox** [comment]
This is OK

**Comment by chaals** [comment]
Isn't the requirement here that we have reliable signatures based on cryptography?

**Comment by kubasiemion** [comment]
Agreed to be closed - global assumptions PR pending
