### ISSUE TITLE
Privacy Layer Integration

### ISSUE THREAD

**Issue by saltiniroberto** [EntEthAlliance/enhanced-bft#18]
If the *BFT consensus protocol is to be integrated with a privacy layer, then the privacy layer must always allow the *BFT validators to access enough data to validate blocks.

**Comment by drequinox** [comment]
Let us keep layer 2 separate. If this is a requirement, please provide some use cases and potential benefits this approach may provide. Also, define ‘enough’ what data precisely?

**Comment by chaals** [comment]
@saronimo and others have made the point in the EEA spec that it is pretty critical that nodes can form consensus on blockchains that allow private transactions. The separation may imply a significant set of requirements on how private transactions are handled, so it may be reasonable to consider that as part of the consensus algorithm itself.

> Also, define ‘enough’ what data precisely?

"enough to validate blocks" makes the answer to that question a direct property of the mechanism by which blocks are validated, no?

**Comment by kubasiemion** [comment]
I suggest that we say: the complete state of the EEA compliant blockchain, including private sub-states, must pass validation. (Then there is a hackton of exciting details how the private state is differently validated, but the point is that some validation is there).

**Comment by kubasiemion** [comment]
Closed as agreed
