### ISSUE TITLE
GST is assumed to be eventually reached

### ISSUE THREAD

**Issue by saltiniroberto** [EntEthAlliance/enhanced-bft#2]
**[GPAv1](https://member.entethalliance.org/HigherLogic/System/DownloadDocumentFile.ashx?DocumentFileKey=8eaf71f6-6cd1-4720-bada-4c7f3030197c) feedback**
GPAv1 states “The proposed algorithms to address the ‘limitation’ in IBFT where it is not guaranteed that a transaction added to the local ledger of an honest node will eventually be added to other honest nodes’ local ledger. [...] the problem here is that **this scenario seems possible only if a particular type of event called Global stabilization time (GST) is never reached.** [...].
Are there any scenarios with empirical evidence that GST cannot happen in IBFT, have this scenario been seen on a physical network?

**Reply**
The claim highlighted in bold above is not correct (probably based on a misunderstanding of some sort).
It is not true that either the “Correctness Analysis of IBFT” or the Gray Paper consider cases where GST is never reached. **Both papers only consider cases where GST is a finite value and therefore it will always be eventually reached**.
The scenarios proving that there is no guarantee that a transaction is added to the local ledger and that there is no guarantee that a block is eventually received by all honest node are possible under this condition (GST is eventually reached)

**Comment by kubasiemion** [comment]
Closing, as we have agreed to include the relevant content into Glossary and Assumptions (meerting 31.07.2019)
