### ISSUE TITLE
Consolidate all terminology-related "issues" 

### ISSUE THREAD

**Issue by kubasiemion** [EntEthAlliance/enhanced-bft#25]
We have terminology discussion spread over a number of separate "issues". This is suboptimal.

**Comment by libby** [comment]
Here is a start for the terminology list https://github.com/EntEthAlliance/enhanced-bft/pull/26 please edit / modify away.

**Comment by kubasiemion** [comment]
Closing, as we have agreed to include the relevant content into Glossary and Assumptions (meeting 31.07.2019)
