### ISSUE TITLE
Decide on the folder structure for the repo to accomodate different documents.

### ISSUE THREAD

**Issue by saltiniroberto** [EntEthAlliance/enhanced-bft#43]
At the last F2F in Seattle, it was decided to have spec documents composed by multiple documents. 
Some of these documents are simple one-file documents, others, like the specifications, may be composed of multiple files (e.g main document + images).
We, therefore, need to decide how to structure the folder structure of the repo to accommodate for multiple documents.

**Comment by kubasiemion** [comment]
Any structure already in mind_ A concrete proposal would kick/start a discussion...

**Comment by kubasiemion** [comment]
Closed as agreed on 27th May 2020
