### ISSUE TITLE
When does GST happen?

### ISSUE THREAD

**Issue by saltiniroberto** [EntEthAlliance/enhanced-bft#5]
**[GPAv1](https://member.entethalliance.org/HigherLogic/System/DownloadDocumentFile.ashx?DocumentFileKey=8eaf71f6-6cd1-4720-bada-4c7f3030197c) feedback**
GPAv1 asks 
“When and how GST occurs is not clear from the paper?”

**Reply**
Protocol operating In the eventually synchronous network model, see Issue #4 and Dwork et al. (https://groups.csail.mit.edu/tds/papers/Lynch/jacm88.pdf), are required to operate correctly independently of when this event happens. All that the model guaranteed is that GST will eventually happen.

**Comment by kubasiemion** [comment]
Closing, as we have agreed to include the relevant content into Glossary and Assumptions (meeting 31.07.2019)
