### ISSUE TITLE
Improvements

### ISSUE THREAD

**Issue by saltiniroberto** [EntEthAlliance/enhanced-bft#6]
**[GPAv1](https://member.entethalliance.org/HigherLogic/System/DownloadDocumentFile.ashx?DocumentFileKey=8eaf71f6-6cd1-4720-bada-4c7f3030197c) feedback**
GPAv1 states
“Finally, section 5 of the grey paper provides improvements that can be made in the proposed BFT
Variant but have not been implemented in an existing client yet. Improvements themselves based on justifications provided do seem logical and they could be applied with some variations to both IBFTand other BFT variants”

**Reply**
I agree. We should create one GitHub issue for each of the improvements so that we can decided on which ones to included in the final spec, which ones to leave out and which ones to include but with modifications.

**Comment by chaals** [comment]
suggest we close this issue, it's administrative and describes how we are currently working.

**Comment by kubasiemion** [comment]
Agreed to be closeed
