### ISSUE TITLE
Optimal Byzantine Safety Threshold

### ISSUE THREAD

**Issue by saltiniroberto** [EntEthAlliance/enhanced-bft#7]
**[GPAv1](https://member.entethalliance.org/HigherLogic/System/DownloadDocumentFile.ashx?DocumentFileKey=8eaf71f6-6cd1-4720-bada-4c7f3030197c) feedback**
GPAv1 states “Also note that in a related article here: https://pegasys.tech/another-day-another-consensusalgorithm-why-ibft-2-0/, it is suggested that to address a similar limitation described in Lemma 9, in proposed BFT Variant, 4 validators are required to reach agreement. Is that not a direct violation of optimal byzantine safety threshold? It seems that, in proposed BFT Variant, the threshold of honest nodes required is being increased up to ~80% as opposed to usual and optimal ~67%.”

**Reply**
The Optimal Byzantine Safety Threshold states what the maximum number of Byzantine nodes is, not what the minimum number of honest node is.
In more details, as proved in Dwork et al. (https://groups.csail.mit.edu/tds/papers/Lynch/jacm88.pdf), the maximum number of Byzantine nodes for a network of _n_ nodes is _floor_((_n_-1)/3).
So for a network of 5 validators, the maximum number of Byzantine validators is 1 which implies that we must assume that at least 4 validators are non-Byzantine.

**Comment by kubasiemion** [comment]
This should go into requirements

**Comment by kubasiemion** [comment]
close

**Comment by kubasiemion** [comment]
Close

**Comment by kubasiemion** [comment]
Closed as agreed on Aug 14th
