### ISSUE TITLE
Safety issue in the case of 6 validators

### ISSUE THREAD

**Issue by saltiniroberto** [EntEthAlliance/enhanced-bft#8]
**[GPAv1](https://member.entethalliance.org/HigherLogic/System/DownloadDocumentFile.ashx?DocumentFileKey=8eaf71f6-6cd1-4720-bada-4c7f3030197c) feedback**
GPAv1 asks 
“If the network is partitioned into three nodes each in a six validator network, then any BFT algorithm with even a single Byzantine process can result in violation of safety?”

**Reply**
This is not a general issue of any BFT algorithm.
If the number of required Prepare, Commit messages and Commit seals is increased from 3 to 4 as indicated in the “Correctness Analysis of IBFT” paper then this issue cannot occur anymore.

**Comment by kubasiemion** [comment]
Closing, as we have agreed to include the relevant content into Glossary and Assumptions (meeting 31.07.2019)
