### ISSUE TITLE
Question on the likelihood of network partitioning

### ISSUE THREAD

**Issue by saltiniroberto** [EntEthAlliance/enhanced-bft#9]
**[GPAv1](https://member.entethalliance.org/HigherLogic/System/DownloadDocumentFile.ashx?DocumentFileKey=8eaf71f6-6cd1-4720-bada-4c7f3030197c) feedback**
GPAv1 asks:
“how likely is it that 50% network?”

**Reply**
The only way to reply to this question is by building a probabilistic model of the network which is an extremely time and resourcing consuming exercise that in the best case scenario just yields a statistical, but non certain, answer as any measurement of the present situation may not reflect the network situation in 1,2,5 year time.

**Comment by kubasiemion** [comment]
Closing, as we have agreed to include the relevant content into Glossary and Assumptions (meeting 31.07.2019)
